### ISSUE TITLE
Add something to send custom messages 

### ISSUE THREAD

**Issue by ticaki** [foxriver76/ioBroker.notification-manager#2]
Hinzufügen eines State(Objekt) oder sentTo-Befehls(Scriptadapter) um eigene Benachrichtigungen zu versenden.

**Comment by foxriver76** [comment]
It is now possible with `1.0.0` to register notifications in the ioBroker notification system, which can then be handled by the notification manager of course.

https://github.com/foxriver76/ioBroker.notification-manager#registering-user-centric-notifications

Maybe "real" custom messages could also be a part at some time if needed, but currently I am unsure if this should be the scope and why it would be beneficial sending the message to the notification manager instead of the messaging adapter.
